version: "3"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    command: hbbs -r 223.130.146.32:21116
    restart: unless-stopped
    ports:
      - "21115:21115"         # Changed external port
      - "21116:21116"         # Changed external port
      - "21116:21116/udp"     # Changed external port
      - "21117:21117"         # Changed external port
    volumes:
      - rustdesk-data:/root

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbr
    restart: unless-stopped
    ports:
      - "31118:21118"
    volumes:
      - rustdesk-data:/root

volumes:
  rustdesk-data:

